apiVersion: v1
kind: Service
metadata:
  name: mysqldeploymentservice
spec:
  selector:
    app: mysqlecommercesandbox
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlecommercesandbox
  template:
    metadata:
      labels:
        app: mysqlecommercesandbox
    spec:
      containers:
        - name: mysqlecommercesandbox
          image: mysql
          env:
            - name: MYSQL_DATABASE
              value: "ecommercesandbox"
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysqlstorage
              mountPath: /var/lib/mysql
      volumes: 
        - name: mysqlstorage
          hostPath:
            path: /home/roger/utils/ecommerceMysqlVolume/
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backendecommercesandbox
  template:
    metadata:
      labels:
        app: backendecommercesandbox
    spec:
      containers:
        - name: backendecommercesandbox
          image: rogeralbuquerque/ecommercesandbox_backend:v1
          env:
            - name: DB_HOST
              value: "mysqldeploymentservice"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "ecommercesandbox"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "admin"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backenddeploymentservice
spec:
  selector:
    app: backendecommercesandbox
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
