apiVersion: v1
kind: Service
metadata:
  name: mysqldeploymentservice
spec:
  selector:
    app: mysqldeployment
  ports:
  - protocol: TCP
    port: 3306
  type: ClusteIp 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysqlecommercesandbox
  template:
    metadata:
      labels:
        app: mysqlecommercesandbox
    spec:
      containers:
        - name: mysqlecommercesandbox
          image: mysql
          env:
          - name: MYSQL_DATABASE
            value: "ecommercesandbox"
          - name: MYSQL_ROOT_PASSWORD
            value: "admin"
          ports:
            port: 3306
          volumeMounts:
            - name: mysql_storage
              mountPath: /var/lib/mysql
      volumes: 
        - name: mysql_storage
          hostPath:
            path: /home/roger/utils/ecommerceTools/mysqlVolume
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backendecommercesandbox
  template:
    metadata:
      labels:
        app: backendecommercesandbox
    spec:
      containers:
        - name: backendecommercesandbox
          image: rogeralbuquerque/ecommercesandbox_backend:v1
          env:
          - name: DB_HOST
            value: "mysqlecommercesandbox"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "ecommercesandbox"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "admin"
          ports:
            containerPort: 8080
            targetPort: 8080 

---
apiVersion: v1
kind: Service
metadata:
  name: backenddeploymentservice
spec:
  selector:
    app: backendecommercesandbox
  ports:
  - protocl: TCP
    port: 8080
    type: NodePort
