networks:
  ecommerce_sandbox_network:
    driver: bridge

services:
  ecommercesandbox_mysql:
    image: mysql:latest
    restart: always
    env_file:
      - ./dockerConfigs/envFiles/mysqlEnvFile.env
    volumes:
      - ~/utils/ecommerceMysqlVolume/:/var/lib/mysql
      - ./backend/MysqlBackup:/docker-entrypoint-initdb.d
    networks:
      - ecommerce_sandbox_network


  ecommercesandbox_backend:
    depends_on:
      - ecommercesandbox_mysql
    image: rogeralbuquerque/ecommercesandbox_backend:v1
    restart: always
    env_file:
      - ./dockerConfigs/envFiles/backendEnvFile.env
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - ecommerce_sandbox_network
  
  ecommercesandbox_frontend:
    depends_on:
      - ecommercesandbox_backend
    image: rogeralbuquerque/ecommercesandbox_frontend:v1
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
      INTERNAL_API_URL: http://ecommercesandbox_backend:8080
    networks:
      - ecommerce_sandbox_network

    
    



 
  
