apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommercesandboxfrontdeployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: ecommercesandboxfront
  template:
    metadata:
      labels:
        app: ecommercesandboxfront
    spec:
      containers:
        - name: ecommercesandboxfrontend
          image: rogeralbuquerque/ecommercesandbox_frontend:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: deploymentservice
spec:
  selector:
    app: ecommercesandboxfront
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30000
  type: NodePort
---

